openapi: 3.0.3
info:
  title: TestFire - Admin AddUser (Fixed Token)
  version: 1.0.0
servers:
  - url: https://demo.testfire.net

# This format is 100% supported by the action
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT   # doesn't matter what we write here
security:
  - bearerAuth: YW5OdGFYUm86WkdWdGJ6RXlNelE9Oj9lPz8/P2c=   # ← your exact token

paths:
  /api/admin/addUser:
    post:
      summary: Admin Add User – Fixed Token
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstname
                - lastname
                - username
                - password1
                - password2
              properties:
                firstname: { type: string }
                lastname:  { type: string }
                username:  { type: string }
                password1: { type: string }
                password2: { type: string }
      responses:
        '200': { description: OK }
