openapi: 3.0.0
info:
  title: Admin AddUser API
  version: 1.0.0

servers:
  - url: http://localhost

paths:
  /api/admin/addUser:
    post:
      summary: Add a new user (Admin only)
      description: This API allows the admin to add a new user.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                role:
                  type: string
              required:
                - username
                - email
                - role
      responses:
        "200":
          description: User added successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "500":
          description: Server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

x-zap:
  auth:
    type: header
    headerName: Authorization
    headerValue: "Bearer YW5OdGFYUm86WkdWdGJ6RXlNelE9Oj9lPz8/P2c="
